/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DIHADRONMODULATIONPDF
#define DIHADRONMODULATIONPDF

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class dihadronModulationPDF : public HS::FIT::RooHSEventsPDF {
public:
  dihadronModulationPDF() {} ; 
  dihadronModulationPDF(const char *name, const char *title,
	      RooAbsReal& _Phih,
	      RooAbsReal& _PhiR,
	      RooAbsReal& _helicity,
	      RooAbsReal& _a0,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _a3,
	      RooAbsReal& _a4,
	      RooAbsReal& _a5,
	      RooAbsReal& _a6);
  dihadronModulationPDF(const dihadronModulationPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new dihadronModulationPDF(*this,newname); }
  inline virtual ~dihadronModulationPDF() { }

protected:

  RooRealProxy Phih ;
  RooRealProxy PhiR ;
  RooRealProxy helicity ;
  RooRealProxy a0 ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy a3 ;
  RooRealProxy a4 ;
  RooRealProxy a5 ;
  RooRealProxy a6 ;
  
  Double_t evaluateData() const ;
  Double_t evaluateMC(const vector<Float_t> *vars,const  vector<Int_t> *cats) const ;
  void MakeSets();

private:

  ClassDef(dihadronModulationPDF,1) // Your description goes here...
};
 
#endif
